#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
if(file_exists(__DIR__ . '/config/generated/web.dev.php')){
    $config_filename = __DIR__ . '/config/generated/console.dev.php';
    defined('YII_ENV') || define('YII_ENV', 'dev');
    defined('YII_DEBUG') or define('YII_DEBUG', true);
}else{
    $config_filename = __DIR__ . '/config/console.php';
    defined('YII_ENV') || define('YII_ENV', 'prod');
    defined('YII_DEBUG') or define('YII_DEBUG', false);
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$application = new yii\console\Application(require($config_filename));
$exitCode = $application->run();
exit($exitCode);